#!/bin/bash
#
#$ cpupower  frequency-info
#analyzing CPU 0:
#  driver: BCM2835 CPUFreq
#  CPUs which run at the same hardware frequency: 0 1 2 3
#  CPUs which need to have their frequency coordinated by software: 0 1 2 3
#  maximum transition latency: 355 us.
#  hardware limits: 600 MHz - 900 MHz
#  available frequency steps: 600 MHz, 900 MHz
#  available cpufreq governors: conservative, ondemand, userspace, powersave, performance
#  current policy: frequency should be within 600 MHz and 900 MHz.
#                  The governor "ondemand" may decide which speed to use
#                  within this range.
#  current CPU frequency is 600 MHz (asserted by call to hardware).
#

performance="ondemand"

if [ $(cat /proc/cpuinfo |grep ^Hardware|grep BCM270[89]| wc -l) -eq 0 ] ; then
        exit
fi

echo -n "  $(basename $0) - tuning Raspberry Pi...\n "

if [ -d /sys/devices/system/cpu/cpu0/cpufreq/ ]
    then
        for CPU in /sys/devices/system/cpu/cpu[0-9]/cpufreq/
         do
         echo $performance > $CPU/scaling_governor
         cat $CPU/scaling_governor
        done
fi

echo "Done."
